<?php
// session_start(); 
?>
<html>
    <body>
        <h2>
            Do login
        </h2>

        <?php echo $this->tag->form("login/random"); ?>
            <p>
            <?php 
                // if(isset($message)){ 
                //     echo $message;
                // } 
            ?>

            </p>

                <p>
                    <label for="name">Name</label>
                    <?php echo $this->tag->textField("username"); ?>
                </p>

                <p>
                    <label for="email">E-Mail</label>
                    <?php echo $this->tag->textField("password"); ?>
                </p>

                <p>
                    <?php echo $this->tag->submitButton("Login"); ?>
                </p>

        </form>
        <!-- <form action="login/random" method="POST">
            <label> Username <input type="text" placeholder="Username..." name="username"></label><br>
            <label> Password <input type="text" placeholder="Password..." name="password"></label><br>
            <input type="submit" name="submit" value="Login">
        </form> -->
    </body>
</html>
