<?php
// session_start();
// print_r($_SESSION);
// die();
if(!isset($_SESSION['login'])){
    header('Location:http://localhost:8080/login');
}
print_r($_SESSION['login']);
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>Document</title>
</head>
<body>
<div class="container mt-5">
  <h3>Post Your Blog</h3>
<?php 
            $this->view->message = "Post succesfully";
  if(isset($message)){
    echo $message;
  }
?>
<?php echo $this->tag->form("post/pst"); ?>
                <p>
                 <label for="name">Title</label>

                <?php echo $this->tag::textField([
                      'title',
                      'name'=>'title'
                      ]); ?>
                </p>

                <p>
                <label for="name">Content</label>
                <?php echo $this->tag::textField([
                      'content',
                      'name'=>'content'
                      ]); ?>
                </p>
                <p>
                    <?php echo $this->tag::hiddenField([
                      'user_id',
                      'value'=>$_SESSION['login']['id']
                    ]);
                          
                    ?>
                </p>
                <p>
                    <?php echo $this->tag::submitButton([
                      'Submit',
                    ]);
                    ?>
                </p>
        </form>
        </div>


<!-- <form action="post/pst" method="POST">
  <div class="mb-3">
    <label for="exampleInputEmail1" class="form-label">Title</label>
    <input type="text" class="form-control" name="title" id="title" >
    <input type="hidden" class="form-control" value="<?php echo $_SESSION['login']['id']; ?>" name="id" id="title" >
  </div>
  <div class="mb-3">
    <label for="exampleInputPassword1" class="form-label">Content</label>
    <input type="text" class="form-control" name="content" id="content">
  </div>

  <input type="submit" name="submit" class="btn btn-primary" value="Submit"></button>
</form> -->
    

<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
</body>
</html>