<?php
// foreach($tum as $val){
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>Document</title>
</head>
<body>
<?php
print_r($_SESSION['login']);
    if(isset($_SESSION['login'])){
        $id = $_SESSION['login']['id'];
        // echo $id;
    }
    ?>
    <div class="row mt-5">
        <div class="col-2 row bg-success ">
            <a class="text-danger p-4" href="edit">your post</a>
            
        </div>
        <div class="col-2 row bg-success ">
            <?php if(isset($_SESSION['login'])){
                    if($_SESSION['login']['user_is'] == '1'){ ?>
                            <a class="text-danger p-4" href="dash"> Dashboard</a> 
                    <?php }else{?>
                        <a class="text-danger p-4" href="login"> Login</a> 
                    <?php } ?>
            
                <?php  }  ?>  
        
            
        
        </div>
        <div class="col-2 row bg-success ">
        <a class="text-danger p-4" href="login"> Login</a> 

        </div>
        
        <div class="col-2 row bg-success ">
        <a class="text-danger p-4" href="post"> Add Post</a> 

        </div> 
        <div class="col-2 row bg-success ">
        <!-- <a class="text-danger p-4" href="user"> Users</a>  -->
        <?php echo  $this->tag->linkto('user','Users') ?>

        </div>
        <div class="col-2 row bg-success ">
        <!-- <a class="text-danger p-4" href="user"> Users</a>  -->
        <?php 
            if(isset($_SESSION['login'])){
                echo  $this->tag->linkto('logout','Logout');
            } 
        ?>

        </div>
    </div>
    <?php echo  $this->tag->linkto('user/signup','Signup') ?>

<div class="container">
        <h3 class="text-center"> Blogs ... </h3>
        <?php
    foreach($tum as $tal){
        // foreach($tal as $val){
            if($tal->status == "approved"){
    ?>
    <div class="text-center">
        <div class="card mb-5" style="width: 18rem;">
        <div class="card-body">
            <h5 class="card-title text-center text-danger"><?php echo $tal->title; ?></h5>
            <h6 class="card-subtitle mb-2 text-muted">Card subtitle</h6>
            <p class="card-text"><?php echo $tal->content; ?>.</p>
            <a href="#" class="card-link">Card link</a>
            <a href="#" class="card-link">Another link</a>
        </div>
        </div>
        </div>
<?php }}  ?>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
</body>
</html>


