<h2>Sign up using this form</h2>

<?php echo $this->tag->form(""); ?>
    <p>
    <?php 
        if(isset($message)){ 
            echo $message;
        } 
    ?>

</p>

    <p>
        <label for="name">Name</label>
        <?php echo $this->tag->textField("username"); ?>
    </p>

    <p>
        <label for="email">E-Mail</label>
        <?php echo $this->tag->textField("password"); ?>
    </p>

    <p>
        <?php echo $this->tag->submitButton("Register"); ?>
    </p>

</form>